credentials:
  usernames:
    admin:
      email: admin@congty.com
      name: Quản trị viên
      password: 'Cns@2026@'
      recovery_pin: '1234'
cookie:
  expiry_days: 30
  key: key_bi_mat_cua_ban
  name: app_dang_nhap
